name: 'Destroy Dev Environment'

on:
  workflow_dispatch:
    inputs:
      confirmation:
        description: 'Type "destroy-the-dev-environment" to confirm.'
        required: true
        type: string

permissions:
  id-token: write
  contents: read

jobs:
  terraform-destroy:
    name: 'Terraform Destroy Dev'
    runs-on: ubuntu-latest
    environment: dev
    
    # Define the confirmation phrase as an environment variable
    env:
      CONFIRMATION_PHRASE: 'destroy-the-dev-environment'

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    # Your new safety-check step
    - name: 'Verify Destroy Confirmation'
      run: |
        if [ "${{ github.event.inputs.confirmation }}" != "${{ env.CONFIRMATION_PHRASE }}" ]; then
          echo "❌ ERROR: Confirmation phrase did not match. Aborting workflow."
          exit 1
        else
          echo "✅ Confirmation phrase matches. Proceeding with destroy operation."
        fi

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: arn:aws:iam::456202167790:role/githubaction
        aws-region: us-east-1 

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.13.1

    - name: Terraform Init
      run: terraform init
      working-directory: ./environments/dev

    - name: Terraform Destroy
      run: terraform destroy -auto-approve
      working-directory: ./environments/dev