name: 'Destroy Dev Environment'

on:
  workflow_dispatch:
    inputs:
      confirmation:
        description: 'Type "destroy-the-dev-environment" to confirm.'
        required: true
        type: string

permissions:
  id-token: write
  contents: read

jobs:
  terraform-destroy:
    name: 'Terraform Destroy Dev'
    runs-on: ubuntu-latest
    environment: dev
    
    env:
      CONFIRMATION_PHRASE: 'destroy-the-dev-environment'

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: 'Verify Destroy Confirmation'
      run: |
        if [ "${{ github.event.inputs.confirmation }}" != "${{ env.CONFIRMATION_PHRASE }}" ]; then
          echo "❌ ERROR: Confirmation phrase did not match. Aborting workflow."
          exit 1
        else
          echo "✅ Confirmation phrase matches. Proceeding with destroy operation."
        fi
        
    - name: Setup Python
      uses: actions/setup-python@v5 
      with:
        python-version: '3.9'

    # --- THIS IS THE FIX ---
    # This step now creates all THREE required zip files.
    - name: Create Lambda Deployment Packages for Plan
      run: |
        echo "--- Packaging Preprocessing Lambda ---"
        pip install -r src/lambda_function/requirements.txt -t ./build/lambda_package
        cp src/lambda_function/main.py ./build/lambda_package/
        cd ./build/lambda_package
        zip -r ../lambda_function.zip .
        cd ../..

        echo "--- Packaging API Lambda ---"
        mkdir -p ./build/api_lambda_package
        cp src/api_lambda/main.py ./build/api_lambda_package/
        cd ./build/api_lambda_package
        zip -r ../api_lambda.zip .
        cd ../..
        
        echo "--- Packaging Upload Lambda ---"
        mkdir -p ./build/upload_lambda_package
        cp src/upload_lambda/main.py ./build/upload_lambda_package/
        cd ./build/upload_lambda_package
        zip -r ../upload_lambda.zip .
      working-directory: ${{ github.workspace }}

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: arn:aws:iam::456202167790:role/githubaction
        aws-region: us-east-1 

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.13.1 # Using a valid, recent version

    - name: Terraform Init
      run: terraform init
      working-directory: ./environments/dev

    - name: Terraform Destroy
      run: terraform destroy -auto-approve
      working-directory: ./environments/dev